version: '3'

services:
  user:
    build:
      context: .
      dockerfile: ./user/Dockerfile
    image: ms_user
    container_name: ms_user
    env_file:
      - ./user/.env
    ports:
      - "8008:8008"

  feedback:
    build:
      context: .
      dockerfile: ./feedback/Dockerfile
    image: ms_feedback
    container_name: ms_feedback
    env_file:
      - ./feedback/.env
    ports:
      - "8009:8009"
